import { Activity, BarChart3, Check, CheckCircle2, Clock3, DollarSign, FileText, LockKeyhole, ArrowLeft, Share2, Target, TrendingUp, Users2, X } from "lucide-react";
import { Link, useParams } from "wouter";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { useAuth } from "@/_core/hooks/useAuth";
import { useState } from "react";
import { trpc } from "@/lib/trpc";

const labels: Record<string, string> = { my_assets: "My assets", shared_with_me: "Shared with me", teams: "Teams", knowledge_hub: "Knowledge hub", requests: "Requests", approvals: "Approvals", analytics: "Analytics", audit: "Audit", settings: "Settings" };
const roleLabel = (role?: string) => role === "top_manager" ? "Top Manager" : role === "manager" ? "Manager" : "Team Member";
const roleSections: Record<string, readonly string[]> = {
  top_manager: ["my_assets", "shared_with_me", "teams", "knowledge_hub", "requests", "approvals", "analytics", "audit", "settings"],
  manager: ["my_assets", "shared_with_me", "teams", "knowledge_hub", "requests", "approvals", "analytics"],
  team_member: ["my_assets", "shared_with_me", "knowledge_hub", "requests"],
};

type AssetCardData = { id: string; assetKey: string; name: string; type: string; status: string; businessValue: string | null; estimatedHoursSaved: number; estimatedCostSaved: number };

function AssetCards({ items, emptyMessage }: { items: AssetCardData[]; emptyMessage: string }) {
  if (!items.length) return <div className="rounded-xl border border-dashed border-white/10 p-8 text-center text-sm text-slate-500">{emptyMessage}</div>;
  return <div className="grid gap-3 md:grid-cols-2">{items.map(asset => <Link key={asset.id} href={`/asset/${asset.id}`} className="rounded-xl border border-white/[0.07] bg-white/[0.03] p-5 transition hover:border-cyan-300/30 hover:bg-cyan-300/[0.04]"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="truncate text-sm font-semibold text-white">{asset.name}</div><div className="mt-1 text-xs text-slate-500">{asset.assetKey} · {asset.type}</div></div><Badge className="border border-cyan-300/20 bg-cyan-300/10 text-cyan-200">{asset.status.replace(/_/g, " ")}</Badge></div><p className="mt-4 line-clamp-3 text-xs leading-5 text-slate-400">{asset.businessValue || "No business value has been documented yet."}</p><div className="mt-4 flex gap-4 text-[11px] text-slate-500"><span>{asset.estimatedHoursSaved || 0}h saved</span><span>{asset.estimatedCostSaved || 0} cost saved</span></div></Link>)}</div>;
}


function ImpactAnalytics({ data, role }: { data: { activeAssets: number; pendingApprovals: number; hoursSaved: number; totalCostSaved: number; impactAssets: number; teamScores: Array<{ teamId: string; team: string; successful: number; hoursSaved: number; costSaved: number; score: number }>; topContributors: Array<{ userId: string; user: string; uploads: number; successful: number; hoursSaved: number; score: number }> } | null | undefined; role: string }) {
  const hours = data?.hoursSaved ?? 0;
  const cost = data?.totalCostSaved ?? 0;
  const impactAssets = data?.impactAssets ?? 0;
  const leader = data?.teamScores?.[0];
  const roleName = role === "top_manager" ? "the organization" : "your team";
  const brief = !data ? "Impact reporting will appear when governed asset data is available." : impactAssets === 0 ? `No quantified impact has been recorded for ${roleName} yet. Add hours and cost saved when documenting each asset.` : `${leader?.team || "The leading team"} is currently creating the strongest measured impact, while ${hours.toLocaleString()} hours and ${cost.toLocaleString()} in cost savings have been documented across ${impactAssets} assets.`;
  const maxHours = Math.max(1, ...(data?.teamScores ?? []).map(item => item.hoursSaved));
  return <div className="impact-report"><div className="impact-hero"><div><div className="eyebrow"><Activity size={13} /> Executive impact brief</div><h2>Time, effort & cost saved</h2><p>{brief}</p></div><div className="impact-hero-icon"><TrendingUp size={26} /></div></div><div className="impact-kpi-grid"><div className="impact-kpi"><span className="impact-kpi-icon impact-cyan"><Clock3 size={17} /></span><small>Hours saved</small><strong>{hours.toLocaleString()}<em>h</em></strong><label>Recovered engineering capacity</label></div><div className="impact-kpi"><span className="impact-kpi-icon impact-emerald"><DollarSign size={17} /></span><small>Cost saved</small><strong>{cost.toLocaleString()}<em> total</em></strong><label>Documented operational value</label></div><div className="impact-kpi"><span className="impact-kpi-icon impact-violet"><Target size={17} /></span><small>Impact assets</small><strong>{impactAssets}</strong><label>Assets with measured benefit</label></div><div className="impact-kpi"><span className="impact-kpi-icon impact-amber"><BarChart3 size={17} /></span><small>Active assets</small><strong>{data?.activeAssets ?? 0}</strong><label>{data?.pendingApprovals ?? 0} awaiting review</label></div></div><div className="impact-panels"><div className="impact-chart-card"><div className="section-heading"><div><div className="eyebrow">Capacity recovered</div><h3>Hours saved by team</h3></div><Clock3 size={17} className="text-cyan-300" /></div><div className="impact-bars">{(data?.teamScores ?? []).slice(0, 6).map((item, index) => <div className="impact-bar-row" key={item.teamId}><div className="impact-bar-label"><span>{index + 1}. {item.team}</span><strong>{item.hoursSaved.toLocaleString()}h</strong></div><div className="impact-bar-track"><span className={index === 0 ? "impact-bar-leader" : ""} style={{ width: `${Math.max(item.hoursSaved ? 5 : 0, (item.hoursSaved / maxHours) * 100)}%` }} /></div><small>{item.successful} successful releases · {item.costSaved.toLocaleString()} cost saved</small></div>)}{!data?.teamScores?.length && <p className="py-8 text-center text-xs text-slate-500">Team impact data will appear after assets are quantified.</p>}</div></div><div className="impact-chart-card"><div className="section-heading"><div><div className="eyebrow">People creating value</div><h3>Top contributors</h3></div><Users2 size={17} className="text-amber-200" /></div><div className="impact-contributors">{(data?.topContributors ?? []).slice(0, 5).map((item, index) => <div className="impact-contributor" key={item.userId}><span>{String(index + 1).padStart(2, "0")}</span><div><strong>{item.user}</strong><small>{item.successful} successful · {item.uploads} uploads</small></div><b>{item.hoursSaved}h</b></div>)}{!data?.topContributors?.length && <p className="py-8 text-center text-xs text-slate-500">Contributor impact data will appear after assets are quantified.</p>}</div></div></div></div>;
}


type AuditRow = { id: string; action: string; entityType: string; entityId: string | null; assetId: string | null; result: string; metadata: unknown; createdAt: string | Date; actorName: string | null; actorUsername: string | null; assetName: string | null };
const auditActionLabels: Record<string, string> = { asset_created: "Asset created", asset_updated: "Asset updated", asset_submitted: "Asset submitted", asset_approved: "Asset approved", asset_rejected: "Asset rejected", asset_published: "Asset published", file_uploaded: "File uploaded", file_downloaded: "File downloaded", asset_shared: "Asset shared", access_revoked: "Access revoked", role_changed: "Role changed", ownership_transferred: "Ownership transferred" };
function AuditPanel({ data, search, setSearch, action, setAction }: { data: AuditRow[]; search: string; setSearch: (value: string) => void; action: string; setAction: (value: string) => void }) {
  return <div className="audit-report"><div className="audit-summary"><div><div className="eyebrow"><LockKeyhole size={13} /> Governance ledger</div><h2>Every important action, traceable.</h2><p>Review who changed, shared, approved, or downloaded governed engineering knowledge. Sensitive values are never shown here.</p></div><div className="audit-summary-stat"><strong>{data.length}</strong><span>Recent events</span></div></div><div className="audit-toolbar"><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Search actor, username, or asset..." /><select value={action} onChange={event => setAction(event.target.value)}><option value="">All actions</option>{Object.entries(auditActionLabels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></div><div className="audit-list">{data.map(event => { const metadata = event.metadata && typeof event.metadata === "object" ? event.metadata as Record<string, unknown> : {}; const detail = Object.entries(metadata).filter(([key]) => !["password", "passwordHash", "token", "tokenHash"].includes(key)).slice(0, 3).map(([key, value]) => `${key}: ${String(value)}`).join(" · "); return <article className="audit-event" key={event.id}><div className={`audit-event-icon ${event.result === "success" ? "audit-success" : "audit-failure"}`}><Activity size={16} /></div><div className="audit-event-main"><div className="audit-event-top"><strong>{auditActionLabels[event.action] || event.action.replace(/_/g, " ")}</strong><span>{new Date(event.createdAt).toLocaleString()}</span></div><p><b>{event.actorName || event.actorUsername || "System"}</b> · {event.assetName || event.entityType.replace(/_/g, " ")}</p>{detail && <small>{detail}</small>}</div><span className={`audit-result ${event.result === "success" ? "audit-result-success" : "audit-result-failure"}`}>{event.result}</span></article>; })}{!data.length && <div className="audit-empty"><LockKeyhole size={22} /><p>No audit events match the selected filters.</p></div>}</div></div>;
}

export default function Section() {
  const { section = "workspace" } = useParams<{ section: string }>();
  const { user, loading } = useAuth();
  const assetsQuery = trpc.assets.list.useQuery({ limit: 50 }, { enabled: Boolean(user), retry: false });
  const dashboardQuery = trpc.dashboard.snapshot.useQuery(undefined, { enabled: Boolean(user) && section === "analytics", retry: false });
  const [auditSearch, setAuditSearch] = useState("");
  const [auditAction, setAuditAction] = useState("");
  const auditQuery = trpc.administration.listAudit.useQuery({ query: auditSearch || undefined, action: auditAction || undefined, limit: 100 }, { enabled: Boolean(user) && section === "audit", retry: false });
  const myAssetsQuery = trpc.assets.myAssets.useQuery(undefined, { enabled: Boolean(user), retry: false });
  const sharedQuery = trpc.assets.sharedWithMe.useQuery(undefined, { enabled: Boolean(user), retry: false });
  const knowledgeQuery = trpc.assets.knowledgeHub.useQuery(undefined, { enabled: Boolean(user), retry: false });
  const requestsQuery = trpc.assets.requests.useQuery(undefined, { enabled: Boolean(user), retry: false });
  const queueQuery = trpc.governance.managerQueue.useQuery(undefined, { enabled: Boolean(user) && (user?.role === "manager" || user?.role === "top_manager"), retry: false });
  const decide = trpc.assets.decide.useMutation({ onSuccess: () => { void queueQuery.refetch(); void requestsQuery.refetch(); } });
  const smtpQuery = trpc.administration.getSmtpSettings.useQuery(undefined, { enabled: user?.role === "top_manager", retry: false });
  const saveSmtp = trpc.administration.saveSmtpSettings.useMutation({ onSuccess: () => { setSmtpNotice("SMTP settings saved securely."); setSmtpPassword(""); void smtpQuery.refetch(); }, onError: error => setSmtpNotice(error.message) });
  const [smtpHost, setSmtpHost] = useState("");
  const [smtpPort, setSmtpPort] = useState("587");
  const [smtpUsername, setSmtpUsername] = useState("");
  const [smtpPassword, setSmtpPassword] = useState("");
  const [smtpFrom, setSmtpFrom] = useState("");
  const [smtpSecure, setSmtpSecure] = useState(false);
  const [smtpNotice, setSmtpNotice] = useState("");

  if (loading) return <div className="min-h-screen bg-[#080f19] p-8 text-slate-400">Loading access policy...</div>;
  if (!user) return <div className="login-screen"><div className="login-card text-center"><LockKeyhole className="mx-auto text-cyan-300" /><h1 className="mt-4 text-xl font-semibold text-white">Internal access required</h1><Link href="/" className="mt-5 inline-block text-sm text-cyan-300">Return to sign in</Link></div></div>;
  const allowedSections = roleSections[user.role] ?? [];
  if (!allowedSections.includes(section)) return <div className="min-h-screen bg-[#080f19] p-8 text-slate-200"><Link href="/" className="text-cyan-300">Return to ENGHUB</Link><div className="mx-auto mt-16 max-w-xl rounded-2xl border border-rose-400/20 bg-rose-400/[0.04] p-8"><h1 className="text-xl font-semibold text-white">Access restricted</h1><p className="mt-3 text-sm leading-6 text-slate-400">This workspace section is not available for the {roleLabel(user.role)} role.</p></div></div>;

  const title = labels[section] || "Workspace section";
  const relevantQuery = section === "my_assets" ? myAssetsQuery : section === "shared_with_me" ? sharedQuery : section === "knowledge_hub" ? knowledgeQuery : assetsQuery;
  const loadingData = relevantQuery.isLoading || (section === "analytics" && dashboardQuery.isLoading) || (section === "audit" && auditQuery.isLoading) || (section === "requests" && requestsQuery.isLoading) || (section === "approvals" && queueQuery.isLoading);
  const errorData = relevantQuery.isError || (section === "analytics" && dashboardQuery.isError) || (section === "audit" && auditQuery.isError) || (section === "requests" && requestsQuery.isError) || (section === "approvals" && queueQuery.isError);
  const assetItems = (relevantQuery.data ?? []) as AssetCardData[];

  const renderContent = () => {
    if (section === "my_assets") return <AssetCards items={assetItems} emptyMessage="You have not submitted any assets yet." />;
    if (section === "shared_with_me") return <><div className="mb-4 flex items-center gap-2 text-xs text-slate-500"><Share2 size={14} className="text-cyan-300" /> Assets explicitly shared with your user or one of your teams.</div><AssetCards items={assetItems} emptyMessage="No published assets have been shared with you." /></>;
    if (section === "knowledge_hub") return <><div className="mb-4 flex items-center gap-2 text-xs text-slate-500"><Users2 size={14} className="text-cyan-300" /> Published and active assets available for reuse in your governed teams.</div><AssetCards items={assetItems} emptyMessage="The knowledge hub is empty for your teams." /></>;
    if (section === "teams") return <AssetCards items={assetItems} emptyMessage="No assets in your governed team scope." />;
    if (section === "requests") {
      const requests = requestsQuery.data ?? [];
      return requests.length ? <div className="grid gap-3">{requests.map(item => <div key={item.approvalId} className="rounded-xl border border-white/[0.07] bg-white/[0.03] p-5"><div className="flex items-start justify-between gap-4"><div><Link href={`/asset/${item.assetId}`} className="text-sm font-semibold text-white hover:text-cyan-200">{item.name}</Link><div className="mt-1 text-xs text-slate-500">{item.assetKey} · {item.type}</div></div><Badge className="border border-amber-400/20 bg-amber-400/10 text-amber-200">{item.approvalStatus.replace(/_/g, " ")}</Badge></div><div className="mt-4 grid gap-2 text-xs text-slate-400 sm:grid-cols-2"><span>Asset status: {item.assetStatus.replace(/_/g, " ")}</span><span>Requested: {new Date(item.requestedAt).toLocaleString()}</span>{item.decisionNote && <span className="sm:col-span-2">Note: {item.decisionNote}</span>}</div></div>)}</div> : <div className="rounded-xl border border-dashed border-white/10 p-8 text-center text-sm text-slate-500">You have no submitted requests.</div>;
    }
    if (section === "approvals") {
      const approvals = queueQuery.data ?? [];
      return approvals.length ? <div className="grid gap-3">{approvals.map(item => <div key={item.approvalId} className="rounded-xl border border-white/[0.07] bg-white/[0.03] p-5"><div className="flex items-start gap-4"><div className="rounded-lg bg-amber-400/10 p-2 text-amber-200"><Clock3 size={17} /></div><div className="min-w-0 flex-1"><Link href={`/asset/${item.assetId}`} className="truncate text-sm font-semibold text-white hover:text-cyan-200">{item.name}</Link><div className="mt-1 text-xs text-slate-500">{item.assetKey} · {item.type} · submitted {new Date(item.requestedAt).toLocaleString()}</div></div><Badge className="border border-amber-400/20 bg-amber-400/10 text-amber-200">Pending</Badge></div><div className="mt-4 flex flex-wrap gap-2"><Link href={`/asset/${item.assetId}`} className="inline-flex items-center rounded-md border border-cyan-300/30 bg-cyan-300/10 px-3 py-2 text-xs font-semibold text-cyan-100">Inspect asset</Link><Button disabled={decide.isPending} className="create-button" onClick={() => decide.mutate({ approvalId: item.approvalId, decision: "approved" })}><Check size={14} /> Approve</Button><Button disabled={decide.isPending} variant="outline" className="secondary-button" onClick={() => decide.mutate({ approvalId: item.approvalId, decision: "changes_requested", note: "Please update the submission details." })}>Request changes</Button><Button disabled={decide.isPending} variant="outline" className="border-rose-400/20 text-rose-200 hover:bg-rose-400/10" onClick={() => decide.mutate({ approvalId: item.approvalId, decision: "rejected" })}><X size={14} /> Reject</Button></div></div>)}</div> : <div className="rounded-xl border border-dashed border-white/10 p-8 text-center text-sm text-slate-500">No approvals are assigned to you.</div>;
    }
    if (section === "analytics") return <ImpactAnalytics data={dashboardQuery.data} role={user.role} />;
    if (section === "audit") return <AuditPanel data={(auditQuery.data ?? []) as AuditRow[]} search={auditSearch} setSearch={setAuditSearch} action={auditAction} setAction={setAuditAction} />;
    if (section === "audit") return <div className="rounded-xl border border-white/[0.07] bg-white/[0.03] p-5 text-sm text-slate-400">Audit events are append-only and available from each asset detail page.</div>;
    if (section === "settings") return <div className="grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><div className="rounded-xl border border-cyan-300/15 bg-gradient-to-br from-cyan-300/[0.08] to-white/[0.02] p-6"><div className="eyebrow">Mail delivery</div><h2 className="mt-2 text-xl font-semibold text-white">SMTP email server</h2><p className="mt-2 text-xs leading-5 text-slate-400">Configure the server used for secure password reset emails. The password is encrypted before it is stored.</p><div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="field-label">SMTP host<input value={smtpHost || smtpQuery.data?.host || ""} onChange={event => setSmtpHost(event.target.value)} placeholder="smtp.company.com" /></label><label className="field-label">Port<input type="number" value={smtpPort || String(smtpQuery.data?.port || 587)} onChange={event => setSmtpPort(event.target.value)} /></label><label className="field-label">Username<input value={smtpUsername || smtpQuery.data?.username || ""} onChange={event => setSmtpUsername(event.target.value)} placeholder="mailer@company.com" /></label><label className="field-label">From email<input type="email" value={smtpFrom || smtpQuery.data?.fromEmail || ""} onChange={event => setSmtpFrom(event.target.value)} placeholder="ENGHUB <enghub@company.com>" /></label><label className="field-label sm:col-span-2">SMTP password<input type="password" value={smtpPassword} onChange={event => setSmtpPassword(event.target.value)} placeholder={smtpQuery.data ? "Leave empty to keep current password" : "Required"} /></label></div><label className="mt-4 flex items-center gap-2 text-xs text-slate-400"><input type="checkbox" checked={smtpSecure} onChange={event => setSmtpSecure(event.target.checked)} /> Use secure TLS connection</label><Button className="create-button mt-6" disabled={saveSmtp.isPending} onClick={() => saveSmtp.mutate({ host: smtpHost || smtpQuery.data?.host || "", port: Number(smtpPort || smtpQuery.data?.port || 587), secure: smtpSecure || Boolean(smtpQuery.data?.secure), username: smtpUsername || smtpQuery.data?.username || "", password: smtpPassword || undefined, fromEmail: smtpFrom || smtpQuery.data?.fromEmail || "" })}>{saveSmtp.isPending ? "Saving..." : "Save SMTP settings"}</Button>{smtpNotice && <p className="mt-4 text-xs text-cyan-200">{smtpNotice}</p>}</div><div className="rounded-xl border border-white/[0.07] bg-white/[0.03] p-6"><div className="eyebrow">Recovery policy</div><h2 className="mt-2 text-xl font-semibold text-white">Password reset flow</h2><div className="mt-5 space-y-4 text-sm leading-6 text-slate-400"><p>Users request a one-time reset link using their username or company email.</p><p>Links expire after 30 minutes and passwords are hashed server-side.</p><p>The system returns a neutral response so account existence is not exposed.</p></div></div></div>;
    return <div className="rounded-xl border border-white/[0.07] bg-white/[0.03] p-5 text-sm text-slate-400">Analytics will use governed asset activity after the reporting model is enabled.</div>;
  };

  return <div className="min-h-screen bg-[#080f19] text-slate-200"><header className="border-b border-white/[0.07] bg-[#0b1421] px-6 py-4"><div className="mx-auto flex max-w-6xl items-center justify-between"><Link href="/" className="flex items-center gap-2 text-xs text-slate-400 hover:text-cyan-300"><ArrowLeft size={15} /> ENGHUB workspace</Link><Badge className="border border-cyan-400/20 bg-cyan-400/10 text-cyan-200">{roleLabel(user.role)}</Badge></div></header><main className="mx-auto max-w-6xl px-6 py-10"><div className="text-[10px] uppercase tracking-[.22em] text-cyan-300">{section === "approvals" || section === "requests" ? "Governance workspace" : "Engineering workspace"}</div><h1 className="mt-3 text-3xl font-semibold text-white">{title}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-400">Each section is backed by its own governed data: ownership, explicit shares, published knowledge, submitted requests, or assigned approvals.</p><div className="mt-8">{loadingData ? <div className="rounded-xl border border-white/10 p-8 text-center text-sm text-slate-500">Loading governed workspace data...</div> : errorData ? <div className="rounded-xl border border-rose-400/20 bg-rose-400/[0.05] p-8 text-center text-sm text-rose-200">Unable to load this section. Check the API logs and try again.</div> : renderContent()}</div></main></div>;
}

void CheckCircle2;
void FileText;
void LockKeyhole;
